### ISSUE TITLE
J3DModelViewer crashes upon conversion to .obj common file with custom created bdl/bmd from obj2bdl/universalbmdexporter

### ISSUE THREAD

**Issue by thomaslewisjames** [LordNed/J3D-Model-Viewer#1]

**Comment by Kaiotiq** [comment]
Probably a MAT3 section error.

**Comment by LordNed** [comment]
Is this attempting to export models out to the OBJ file format? If so, this feature doesn't work yet. The current workaround is to use bmdview2 to export to obj, or there is a 3ds Max MaxScript format that imports the .bmd straight into 3ds max.
